# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: docker-pull-push
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
brews:
  - tap:
      owner: docker-pull-push
      name: homebrew-docker-pull-push
    folder: Formula
    homepage:  https://github.com/amjad489/docker-pull-push
    description: Migrate docker images from docker hub to AWS ECR.
    license: Apache License 2.0
    install: |-
      bin.install "docker-pull-push"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
